require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.treesitter"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.autopairs"
require "user.toggleterm"
require "user.bufferline"
require "user.lualine"
require "user.telescope"
--require "user.fzf"

--require "fzf"
