require("user.options")
require("user.keymaps")
require("user.plugins_lazy")
-- require("user.treesitter")
require("user.colorscheme")
-- require("user.cmp")
require("user.lsp")
require("user.toggleterm")
require("user.bufferline")
require("user.lualine")
require("user.comment")
require("user.filetype")
require("user.tree-sitter-sdp")
require("user.functions")
