# Path to your oh-my-zsh configuration.
export ZSH=~/.oh-my-zsh


# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="dpoggi"
#ZSH_THEME="zhann"
# ZSH_THEME="gallois"
# ZSH_THEME="agnoster"
# ZSH_THEME="random"
ZSH_THEME="refined"
# ZSH_THEME="taktoa"
# ZSH_THEME="miloshadzic"



# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git osx autojump python node brew)
# plugins=(git osx git-prompt history-substring-search tmux z)
plugins=(git osx git-prompt autojump tmux z)


# TMUX
# Automatically start tmux
# ZSH_TMUX_AUTOSTART=true
# Automatically connect to a previous session if it exists
# ZSH_TMUX_AUTOCONNECT=true

# Enable command auto-correction.
ENABLE_CORRECTION="true"

alias purgeAllBuilds='rm -rf ~/Library/Developer/Xcode/DerivedData/*'

# Set location of z installation
# . /usr/local/etc/profile.d/z.sh

# Set default editor to nvim
export EDITOR='vi'

source $ZSH/oh-my-zsh.sh
# disable all correct
unsetopt correct_all

# Set Spaceship ZSH as a prompt
# autoload -U promptinit; promptinit
# prompt spaceship

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
source ~/.zshrc_local

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
